assets:
  - nica.sql.gz
  - files.tar.gz
steps:
  - name: Upgrade PHP
    plugin: Script
    script: |
      apt-get update -y
      apt-get install software-properties-common -y
      LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y
      apt-get update -y
      apt-get install php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-gd php7.0-fpm php7.0-mbstring php7.0-curl php7.0-zip php7.0-xml php7.0-bcmath --force-yes -y
  - name: Composer install
    command: 'cd /src; composer self-update; composer install --prefer-dist'
  - name: Drupal Setup
    plugin: Drupal
    database: nica.sql.gz
    databaseGzipped: true
    subDirectory: web
    drupalVersion: 8
    settingsAppend: "$config_directories = array(CONFIG_SYNC_DIRECTORY => '../config');"
  - name: Set Files
    command: "cd /assets; tar xvfz /assets/files.tar.gz;
    rm -fd -R var/www/html/sites/default/files/;
    mv /assets/files /var/www/html/sites/default;
    chown www-data:www-data -R /var/www/html/sites/default/files;"
  - name: Configuration Import
    command: 'drush cim -y; drush cr;'
