language: php
sudo: false
php:
- 7
mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8
before_install:
- composer self-update
install:
- mysql -e 'create database drupal_travis_db;'
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- composer global require drush/drush:dev-master
- phpenv rehash
- drush --verbose site-install --db-url=mysql://root:@127.0.0.1/drupal config_installer --yes
notifications:
  slack:
    secure: T9QQJpdmwMYHZCIRrko44u6W1q0qyE91Mu+Gwt1bK1FmGOnmwnhddU0eiAIbJ58GGuVBdlM5BwY2qXSvWvNUymt52n1mNkz222AS+vNrk/SS5B2I3BPMLCSzuL77siZN1xPBXAlKpAHt/CX+4G1A1uPudSFb5mwij1Vc1bSp6mPqOto+En+UGnUUx+ioj/83gxosbmukWgUki5IBNsww7FXLPbGG7ArIBAKNdy4+9azwmjH2qlDtOwKhhZH6zhIU5f7NdJSQx4R/sJbpzODee0aXhySWdl3ezXZMEJ9SoaNdghJsnDAJJFEwKvNpjZ/ejKjMKUn5UrhI/2Y3CVl+ZvC8oG63EN8eg6h0WPlliULswA0y63AGu/2KcNHOBsKbW9GigeqTExOwFdhUVVEWahwkT4ED42pUoOJ4pR6I74ygRnFitMOAwdr0eqYpBW20Wn7+9zW0KS8VzxMQROamNRYb8iyhW4AegMcqVpO/bcXtobk95ozcDSp5U0XY6vKZ7zY9eDLy+TyYqETGs841EyL+gXNXsihyHxm1hL1Bn4CEfwd4eo5gCeR8v3lK4avuWB8mRju41QTpm+50QuL50Bq13EPluzj/1KUuVTmAsc17ZSePtiHSiQcv0NGgIKkQIxVqni3BzoMjTGz7E9U4zOL66UNGHmREWCywgFN4oBw=
